apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
      containers:
        - name: url-shortener
          image: divyapilla75/shortened-url:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/data"
              name: sqlite-storage



#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: url-shortener
#  labels:
#    app: url-shortener
#spec:
#  replicas: 2  # Number of pods
#  selector:
#    matchLabels:
#      app: url-shortener
#  template:
#    metadata:
#      labels:
#        app: url-shortener
#    spec:
#      containers:
#        - name: url-shortener
#          image: divyapilla75/shortened-url:latest  # Use your Docker Hub image
#          ports:
#            - containerPort: 5000
#          env:
#            - name: FLASK_ENV
#              value: "production"
