apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80    # External Port
      targetPort: 5000  # Container Port
  type: NodePort  # Exposes the app on a high port (e.g., 30000-32767)
